version: '3'

services:
  lb:
    image: haproxy
    networks:
      - case
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  pg:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - case
    environment:
      - POSTGRES_DB=teknasyon
      - POSTGRES_USER=teknasyon
      - POSTGRES_PASSWORD=Teknasyon1!
  redis:
    image: redis
    networks:
      - case
  nestapp1:
    build: ./
    networks:
      - case
    depends_on:
      - rmq
      - pg
  nestapp2:
    build: ./
    networks:
      - case
    depends_on:
      - rmq
      - pg
  nestapp3:
    build: ./
    networks:
      - case
    depends_on:
      - rmq
      - pg
networks:
  case:
    driver: bridge
